---
# roles/common/tasks/main.yml
- name: set system locale
  command: update-locale LC_ALL={{ lc_all }} LANG={{ lang }} LC_CTYPE={{ lc_ctype }} LC_COLLATE={{ lc_collate }}

- name: set timezone
  file: src=/usr/share/zoneinfo/{{ common_timezone }}
        dest=/etc/localtime
        force=yes
        state=link

- name: Configure the PostgreSQL APT key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present

- name: Configure the PostgreSQL APT repositories
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ {{ ubuntu_release }}-pgdg main 9.5"
                  state=present

- name: update apt cache
  apt: update_cache=yes

- name: ensure a default bashrc and inputrc file
  copy: src={{ item.src }} dest=/home/{{ user }}/{{ item.dest }} owner={{ user }} group={{ user }}
  with_items:
    - { src: 'bashrc', dest: '.bashrc' }
    - { src: 'inputrc', dest: '.inputrc' }

- name: install apt_get install apt_packages
  apt: pkg={{ item }} state=present
  with_items: base_ubuntu.common.apt_packages

- name: easy_install pip
  easy_install: name=pip

- name: ensure there is a group www-data
  group: name=www-data state=present system=yes
